### ISSUE TITLE
Tags instead of continuous branch

### ISSUE THREAD

**Issue by mc-allen** [ddiakopoulos/tinyply#21]
Can I request tags instead of a continuously changing branch for 2.0? That would help me in the workflow I have, where I am using a build system that downloads a tarball from github and verifies the checksum before installing it. If the branch is changing, this will break often; if immutable tags are used instead, it's robust.

**Comment by ddiakopoulos** [comment]
Hi @mc-allen done

The project is now based on master branch (got rid of the default 2.0 branch which was always supposed to be temporary) and added a 2.1 tag
