### ISSUE TITLE
avoid deleting old releases?

### ISSUE THREAD

**Issue by barcharcraz** [ddiakopoulos/tinyply#22]
Since this github seems to serve as the primary archive of releases it would be good if you could avoid removing releases from the repo. When you do this is breaks any links present in, for example, rpm spec files, or other package metadata files.

Thanks :)

**Comment by ddiakopoulos** [comment]
@barcharcraz can you elaborate? I'm not sure I follow.

**Comment by barcharcraz** [comment]
context:
I maintain https://wrapdb.mesonbuild.com/tinyply which is a build system file that allows easy use of tiny ply as a sub project in meson based projects. When 2.1 was released and 2.0 removed this broke projects using my wrap until I had updated the wrap and they had given their go-ahead (run meson wrap update tinyply).

**Comment by ddiakopoulos** [comment]
Hmm, curious. I don't recall removing 2.0 though. For 2.1 someone asked about creating tagged releases (#21), which was the first instance where I had any release. Going forward, each new update will have a new release and none will be removed, so I don't think there will be further issues.
