### ISSUE TITLE
fail to build on Windows VS2013 x64

### ISSUE THREAD

**Issue by knowthyselfcn** [ddiakopoulos/tinyply#23]
Error	1	error C2280: 'std::unique_ptr<uint8_t,tinyply::Buffer::delete_array> &std::unique_ptr<uint8_t,tinyply::Buffer::delete_array>::operator =(const std::unique_ptr<uint8_t,tinyply::Buffer::delete_array> &)' : attempting to reference a deleted function	tinyply\source\tinyply.cpp	390	1	tinyply

**Comment by ddiakopoulos** [comment]
@knowthyselfcn VS2013 isn't a compiler target for me. Looks like Buffer might need a move and assignment constructor added. I'd be happy to accept a PR to fix this but won't have time to look at it myself.
