### ISSUE TITLE
Using std::vector for propertyKeys ?

### ISSUE THREAD

**Issue by luxigo** [ddiakopoulos/tinyply#26]
I do not want the propertyKeys hardcoded eg for request_properties_from_element(), I want to use std::vector instead of std::initializer_list to allow specifying the property names dynamically.

Maybe there's an obvious solution I cannot see (instead of patching tinyply.h)

My native language is C, I am not as fluent in C++ ... type casting tricks I tried based on what I read on stackoverflow failed, maybe they were dependent on the compiler (options?) or the standard library implementation, anyway I could not manage to make it work with g++

Thanks in advance !

**Comment by ddiakopoulos** [comment]
Hi @luxigo sorry to revive this ancient issue, but I finally fixed this in d5115d669a136bcdaf086bb683ff5bfeb06234ac
