### ISSUE TITLE
Use std::vector<uint8_t> instead of Buffer class

### ISSUE THREAD

**Issue by SunBlack** [ddiakopoulos/tinyply#28]
Currently I don't see any reasons why tinyply is using a Buffer class, which looks equal to a normal `std::vector`. So `Buffer buffer;` in `struct PlyData` could be replaced by `std::vector<uint8_t> buffer;` or `std::unique_ptr<std::vector<uint8_t>> buffer;`

**Comment by ddiakopoulos** [comment]
Since this comment from 2018, the library has gone through several rewrites and the `Buffer` class is presently used to wrap a byte vector with information about stride, or with an assistant buffer that describes the number of variable length elements.
