### ISSUE TITLE
non-const uint8_t*

### ISSUE THREAD

**Issue by tobysharp** [ddiakopoulos/tinyply#40]
In `PlyFile::add_properties_to_element` I notice that argument `uint8_t* data` is a pointer to non-const data. Is this buffer modified by the function? If so, some comment to that effect would be helpful. If not, please change to `const uint8_t* data`.

**Comment by ddiakopoulos** [comment]
Hi @tobysharp thanks - I've fixed/updated this behavior in ca7b279fb6c9af931ffdaed96a3b11ca3ccd79ea. `PlyFile::add_properties_to_element` now respects const input pointers.
