### ISSUE TITLE
Built library is large

### ISSUE THREAD

**Issue by gpanders** [ddiakopoulos/tinyply#9]
The built tinyply library target (`libtinyply.a` in my Cmake project) is 1.6 M. This seems pretty large for a library advertised as "tiny". For comparison, `rply` builds to about 88 K. Is there a way to trim down the final size of the library?

**Comment by ddiakopoulos** [comment]
The _tiny_ qualifier is a nod to the two-file, ~700 LoC structure of the codebase. I didn't imagine that tinyply would be built as a static library. It's just one *.cpp & .h so I figure most people might compile into their apps directly.

Tinyply uses templates and the stl, so there's a variety of code that can't get optimized out at link-time when built statically. For example, the example application is lightweight (~120K) and demonstrates almost every public API function.

**Comment by gpanders** [comment]
Ah, that's just the kind of information I was looking for. I'm still pretty new to the world of C++ development, and CMake builds libraries statically by default. Manually specifying it to build as a shared library cut the size in half.

Thanks!
